name: Test mkr command

on:
  push:
  pull_request:

jobs:
  apt-get:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        curl -fsSL https://mackerel.io/file/script/setup-apt-v2.sh | sh
        sudo apt-get install mkr
        mkr --version
  go-get:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.14
    - run: |
        go get github.com/mackerelio/mkr
        go install github.com/mackerelio/mkr
        mkr --version
